name: Build, publish and deploy to MonsterASP.NET

on: [push]

jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.301

      - name: Install dependencies
        run: dotnet restore Isharp.sln

      - name: Build
        run: dotnet build Isharp.sln --configuration Release --no-restore

      - name: Replace piranha connection string
        shell: pwsh
        run: |
          $file = "Isharp/appsettings.json"
          $json = Get-Content $file -Raw | ConvertFrom-Json
          $json.ConnectionStrings.piranha = "${{ secrets.DB_CONNECTION_STRING_PIRANHA }}"
          $json | ConvertTo-Json -Depth 10 | Set-Content $file -Encoding UTF8

      - name: Publish
        run: dotnet publish Isharp/Isharp.csproj --configuration Release --output ./publish --runtime win-x86 --no-restore

      - name: Test with .NET
        run: dotnet test Isharp.sln

      - name: Deploy to MonsterASP.NET via WebDeploy
        uses: rasmusbuchholdt/simply-web-deploy@2.1.0
        with:
          website-name: ${{ secrets.WEBSITE_NAME }}
          server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
          server-username: ${{ secrets.SERVER_USERNAME }}
          server-password: ${{ secrets.SERVER_PASSWORD }}
